<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SJL4OQ96" failures="1" tests="11" name="Test" time="2.624" errors="0" timestamp="2023-06-17T09:17:28 ICT">
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC01_Validate200Ok" time="0.008"/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC03_MessageContent" time="0.012"/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="saveToken" time="0.003"/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC02_ValidateMessage" time="0.003"/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC03_ValidateToken" time="0.011"/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC05_ValidateUserType" time="0.013"/>
  <testcase classname="com.api.auto.testcase.TC_API_Login" name="TC06_ValidateAccount" time="0.015"/>
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="TC01_Validate201Created" time="0.002">
    <failure type="java.lang.AssertionError" message="Status Check Failed! expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: Status Check Failed! expected [201] but found [200]
at com.api.auto.testcase.TC_API_CreateWork.TC01_Validate201Created(TC_API_CreateWork.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TC01_Validate201Created -->
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="TC03_ValidateNameOfWorkMatched" time="0.015"/>
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="TC04_ValidateExperienceMatched" time="0.01"/>
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="TC05_ValidateEducationMatched" time="0.008"/>
</testsuite> <!-- Test -->
