<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="11" passed="10" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-17T09:17:25 ICT" name="Suite" finished-at="2023-06-17T09:17:28 ICT" duration-ms="2624">
    <groups>
    </groups>
    <test started-at="2023-06-17T09:17:25 ICT" name="Test" finished-at="2023-06-17T09:17:28 ICT" duration-ms="2624">
      <class name="com.api.auto.testcase.TC_API_Login">
        <test-method is-config="true" signature="init()[pri:0, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:25 ICT" name="init" finished-at="2023-06-17T09:17:27 ICT" duration-ms="2294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="TC01_Validate200Ok()[pri:0, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:27 ICT" name="TC01_Validate200Ok" finished-at="2023-06-17T09:17:27 ICT" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_Validate200Ok -->
        <test-method signature="TC03_MessageContent()[pri:0, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:27 ICT" name="TC03_MessageContent" finished-at="2023-06-17T09:17:27 ICT" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_MessageContent -->
        <test-method signature="saveToken()[pri:0, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:27 ICT" name="saveToken" finished-at="2023-06-17T09:17:27 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveToken -->
        <test-method signature="TC02_ValidateMessage()[pri:1, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:27 ICT" name="TC02_ValidateMessage" finished-at="2023-06-17T09:17:27 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_ValidateMessage -->
        <test-method signature="TC03_ValidateToken()[pri:2, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:27 ICT" name="TC03_ValidateToken" finished-at="2023-06-17T09:17:27 ICT" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_ValidateToken -->
        <test-method signature="TC05_ValidateUserType()[pri:3, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:27 ICT" name="TC05_ValidateUserType" finished-at="2023-06-17T09:17:27 ICT" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05_ValidateUserType -->
        <test-method signature="TC06_ValidateAccount()[pri:4, instance:com.api.auto.testcase.TC_API_Login@50b5ac82]" started-at="2023-06-17T09:17:27 ICT" name="TC06_ValidateAccount" finished-at="2023-06-17T09:17:27 ICT" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC06_ValidateAccount -->
      </class> <!-- com.api.auto.testcase.TC_API_Login -->
      <class name="com.api.auto.testcase.TC_API_CreateWork">
        <test-method is-config="true" signature="init()[pri:0, instance:com.api.auto.testcase.TC_API_CreateWork@1e683a3e]" started-at="2023-06-17T09:17:27 ICT" name="init" finished-at="2023-06-17T09:17:28 ICT" duration-ms="170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="TC01_Validate201Created()[pri:0, instance:com.api.auto.testcase.TC_API_CreateWork@1e683a3e]" started-at="2023-06-17T09:17:28 ICT" name="TC01_Validate201Created" finished-at="2023-06-17T09:17:28 ICT" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status Check Failed! expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status Check Failed! expected [201] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.api.auto.testcase.TC_API_CreateWork.TC01_Validate201Created(TC_API_CreateWork.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_Validate201Created -->
        <test-method signature="TC03_ValidateNameOfWorkMatched()[pri:2, instance:com.api.auto.testcase.TC_API_CreateWork@1e683a3e]" started-at="2023-06-17T09:17:28 ICT" name="TC03_ValidateNameOfWorkMatched" finished-at="2023-06-17T09:17:28 ICT" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_ValidateNameOfWorkMatched -->
        <test-method signature="TC04_ValidateExperienceMatched()[pri:3, instance:com.api.auto.testcase.TC_API_CreateWork@1e683a3e]" started-at="2023-06-17T09:17:28 ICT" name="TC04_ValidateExperienceMatched" finished-at="2023-06-17T09:17:28 ICT" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_ValidateExperienceMatched -->
        <test-method signature="TC05_ValidateEducationMatched()[pri:4, instance:com.api.auto.testcase.TC_API_CreateWork@1e683a3e]" started-at="2023-06-17T09:17:28 ICT" name="TC05_ValidateEducationMatched" finished-at="2023-06-17T09:17:28 ICT" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05_ValidateEducationMatched -->
      </class> <!-- com.api.auto.testcase.TC_API_CreateWork -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
